### ISSUE TITLE
compute on MapReduce and Reduce returns gathered value

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaParallel/Dagger.jl#13]
Running `compute` on `MapReduce`/`Reduce` nodes gives the final gathered value. Wouldn't it be preferable to return a `DataNode` instead?

**Comment by shashi** [comment]
Reduce usually results in a value, so it made sense to just give the final result. But now I'm not so sure.

It's possible to move the final reduce step (on the parent) to the `gather` on a reduce node. I agree that would be more consistent and less confusing.

**Comment by pranavtbhat** [comment]
Since Map and Reduce are implemented separately, I guess this issue is resolved. Maybe we can move the keyword argument `get_result` from `reduceblock` to [reduce](https://github.com/shashi/ComputeFramework.jl/blob/master/src/map-reduce.jl#L49) instead?

**Comment by shashi** [comment]
`reduce` functions now just return the answer.
