### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaParallel/Dagger.jl#130]
Would it be possible to make a new release? Looks like there have been 32 commits to master since the last release.

cc: @jpsamaroo

**Comment by jpsamaroo** [comment]
Yes, this is definitely something we need to do and keep on top of. However, because JuliaDB is a large downstream user of Dagger, I'd like at a minimum to ensure that we don't break JuliaDB by tagging a new release. I think we should first setup reverse CI to test JuliaDB.

**Comment by DilumAluthge** [comment]
> I think we should first setup reverse CI to test JuliaDB.

See https://github.com/JuliaParallel/Dagger.jl/issues/132

**Comment by jpsamaroo** [comment]
Waiting on JuliaData/JuliaDB.jl#347, and then we'll cut 0.9
