### ISSUE TITLE
Dagger scheduler very slow for certain graphs

### ISSUE THREAD

**Issue by nmoran** [JuliaParallel/Dagger.jl#179]
I have been experimenting with dagger and am encountering some issues with dramatic slow down for certain graph types. The two gists linked here show a script and input file that recreated one of these cases, where the actual tasks have been replaced by trivial tasks. This is being run with a single thread on a single process to rule out any other effects. The output is as follows which shows the largest portion of the time being taken up in initialisation of the scheduler. See attached for a plot of the dag plotted from the logs. The graph does feature loops which I suspect could be causing the issue, but does not have any cycles.

```
Threads 1
  0.047667 seconds (16.36 k allocations: 935.312 KiB)
187.342801 seconds (3.60 G allocations: 94.353 GiB, 11.38% gc time)
totals = Dict(:compute => 0.762289681,:scheduler_init => 186.317986025,:move => 0.040320222,:finish => 0.003399206)
Dict{Symbol,Float64} with 4 entries:
  :compute        => 0.76229
  :scheduler_init => 186.318
  :move           => 0.0403202
  :finish         => 0.00339921
```

dagger_example.jl
https://gist.github.com/nmoran/56379ee72b338c1e38cd5b6ed916a95b

dsl_file:
https://gist.github.com/nmoran/e199da98e67ad7cf4eed555bd14568cf

![my_graph dot](https://user-images.githubusercontent.com/433344/102602091-f3c92b80-4118-11eb-95b0-0253a68ff96b.png)

**Comment by nmoran** [comment]
Most of the time taken up in the `compute_dag` function with majority in the recursive depth first traversal `order` and `dependents` functions.

**Comment by jpsamaroo** [comment]
Thanks for the great reproducer (and I'm happy to see someone using the built-in graph visualization tools). Looks like somehow the recursion in `dependents` and `noffspring` is *really* harmful to performance; I'll attempt to optimize them to bring that cost down so it doesn't take up a significant amount of time. I should also move the scheduler to do lazy dependency checking, since graphs can be arbitrarily deep, although that might be quite invasive, so it could take a while to implement.

**Comment by jpsamaroo** [comment]
And of course, as you pointed out, `order` is a horrible offender too. I'll also add an optimized implementation for that to my PR.

**Comment by jpsamaroo** [comment]
If you happen to find any other kinds of graphs for which the scheduler performs or initializes very poorly, please do reopen this issue.
