### ISSUE TITLE
Questions on strategies for implementing reduce

### ISSUE THREAD

**Issue by tkf** [JuliaParallel/Dagger.jl#201]
I ran a few benchmarks rather "hostile" to the scheduler with Distributed and Dagger. It's for me to learn how to use Dagger and also to understand its performance properties and figure out the best way to implement `reduce`.

Here's the implementations of reduce I tried:

```julia
using Distributed
@info "Using:" nprocs() Threads.nthreads()

@everywhere begin
    using Dagger
    using Distributed
    using SplittablesBase: halve

    # Partition-based approach:
    function mapreduce_di_partition(
        f,
        op,
        init,
        xs,
        basesize;
        pool = Distributed.default_worker_pool(),
    )
        futures = map(Iterators.partition(xs, basesize)) do chunk
            remotecall(pool, chunk) do chunk
                mapreduce(f, op, chunk; init = init)
            end
        end
        return mapreduce(fetch, op, futures)
    end

    # Partition-based approach:
    function mapreduce_da_partition(f, op, init, xs, basesize)
        thunks = map(Iterators.partition(xs, basesize)) do chunk
            wrapper = delayed() do f, op, init, chunk
                mapreduce(f, op, chunk; init = init)
            end
            wrapper(f, op, init, chunk)
        end
        return mapreduce(collect, op, thunks)
    end

    # Binary tree reduce ("static"):
    mapreduce_da_static(f, op, init, xs, basesize) =
        collect(_mapreduce_da_static(f, op, init, xs, basesize))
    function _mapreduce_da_static(f, op, init, xs, basesize)
        if length(xs) <= basesize
            wrapper = delayed() do f, op, init,xs 
                mapreduce(f, op, xs; init = init)
            end
            return wrapper(f, op, init, xs)
        end
        left, right = halve(xs)
        return delayed(op)(
            _mapreduce_da_static(f, op, init, left, basesize),
            _mapreduce_da_static(f, op, init, right, basesize),
        )
    end

    # Binary tree reduce ("dynamic"):
    function mapreduce_da_dynamic(f, op, init, xs, basesize)
        if length(xs) <= basesize
            return mapreduce(f, op, xs; init = init)
        end
        left, right = halve(xs)
        thunk = delayed(mapreduce_da_dynamic)(f, op, init, right, basesize)
        a = mapreduce_da_dynamic(f, op, init, left, basesize)
        b = collect(thunk)
        return op(a, b)
    end

    # Binary tree reduce ("eager"):
    function mapreduce_da_eager(f, op, init, xs, basesize)
        if length(xs) <= basesize
            return mapreduce(f, op, xs; init = init)
        end
        left, right = halve(xs)
        a = delayed(mapreduce_da_eager)(f, op, init, left, basesize)
        b = delayed(mapreduce_da_eager)(f, op, init, right, basesize)
        return op(collect(a), collect(b))
    end
end

using BenchmarkTools
N = 1024

bdi_partition = @benchmark mapreduce_di_partition(identity, +, 0, 1:N, 1)
display(bdi_partition)
println()
bda_partition = @benchmark mapreduce_da_partition(identity, +, 0, 1:N, 1)
display(bda_partition)
println()
bda_static = @benchmark mapreduce_da_static(identity, +, 0, 1:N, 1)
display(bda_static)
println()
bda_dynamic = @benchmark mapreduce_da_dynamic(identity, +, 0, 1:N, 1)
display(bda_dynamic)
println()
bda_eager = @benchmark mapreduce_da_eager(identity, +, 0, 1:N, 1)
display(bda_eager)
println()
```

With `julia -p32`, this prints:

`di_partition`:

```
BenchmarkTools.Trial:
  memory estimate:  4.97 MiB
  allocs estimate:  141183
  --------------
  minimum time:     181.352 ms (0.00% GC)
  median time:      190.135 ms (0.00% GC)
  mean time:        191.666 ms (0.58% GC)
  maximum time:     213.101 ms (4.22% GC)
  --------------
  samples:          27
  evals/sample:     1
```

`da_partition`:

```
BenchmarkTools.Trial:
  memory estimate:  891.36 MiB
  allocs estimate:  7698846
  --------------
  minimum time:     4.139 s (23.46% GC)
  median time:      4.159 s (16.05% GC)
  mean time:        4.159 s (16.05% GC)
  maximum time:     4.179 s (8.71% GC)
  --------------
  samples:          2
  evals/sample:     1
```

`da_static`:

```
BenchmarkTools.Trial:
  memory estimate:  762.45 MiB
  allocs estimate:  6895474
  --------------
  minimum time:     949.802 ms (0.00% GC)
  median time:      1.333 s (35.10% GC)
  mean time:        1.263 s (29.59% GC)
  maximum time:     1.363 s (34.38% GC)
  --------------
  samples:          5
  evals/sample:     1
```

`da_dynamic`:

```
BenchmarkTools.Trial:
  memory estimate:  56.66 MiB
  allocs estimate:  1663564
  --------------
  minimum time:     5.386 s (0.00% GC)
  median time:      5.386 s (0.00% GC)
  mean time:        5.386 s (0.00% GC)
  maximum time:     5.386 s (0.00% GC)
  --------------
  samples:          1
  evals/sample:     1
```

`da_eager`:

```
BenchmarkTools.Trial:
  memory estimate:  1.83 MiB
  allocs estimate:  17358
  --------------
  minimum time:     10.485 s (0.00% GC)
  median time:      10.485 s (0.00% GC)
  mean time:        10.485 s (0.00% GC)
  maximum time:     10.485 s (0.00% GC)
  --------------
  samples:          1
  evals/sample:     1
```

I tried this with Dagger v0.11.0. Also, if I try this with `JULIA_NUM_THREADS=2` and `-p16`, I see a lot of `error in running finalizer: ErrorException("concurrency violation detected")` and sometimes `error in running finalizer: ErrorException("val already in a list")`.

So, it looks like `da_static` is the closest to Distributed-based implementation `di_partition`. I guess approach `da_static` is the way to go for now? IIUC, `treereduce` in Dagger seems to be doing something like this, too. 

It would be cool if `da_dynamic` were the fastest solution or at least comparable to `da_static` (which is conceivable since this is the "most parallel" algorithm especially when the arguments do not have objects with costly serialization). But I suppose it would require each process to act as a local scheduler? I'd also suspect that this would require Dagger with multi-threading to work robustly. Would it be possible for Dagger to do this at some point?

I also found `da_dynamic` was the fastest in Dagger v0.10.0 but not in v0.10.1 or later. I wonder if it had better support before?

**Comment by jpsamaroo** [comment]
Sorry, I thought I had replied here, but it must have just been offline discussion.

Concurrency errors are expected with multithreading right now, because Distributed is not yet thread-safe. I'm not sure about the finalizer error; if you can provide a stacktrace for that, it would help.

`da_partition` is sub-optimal because it creates multiple scheduler instances (each call to `collect`) and executes them serially; don't do this if you can avoid it. Scheduler start-up time and memory usage is relatively expensive. `da_dynamic` and `da_eager` both suffer from the same issue. The "right way" to use Dagger is to construct the entire graph at once, and do a single `collect` call (or use `Dagger.@spawn` for Dagger's eager mode, which might work better for this case). One day in the future we can consider sharing more state between scheduler so this is less of an issue, but I don't see that as being a good use of time right now.

`da_static` is then the only remaining, idiomatic example. I suspect the issue here is overhead from Distributed operations, and just generally the cost of scheduling so many thunks (2047 in this case). Profiling points to various operations in the core scheduler, some of which can and should be optimized. I'll take a look at how much they can be optimized to bring the runtime down, but I'm not sure we'll ever match (or beat) pure Distributed on a problem like this.

**Comment by tkf** [comment]
Thanks for the explanation!

> The "right way" to use Dagger is to construct the entire graph at once,

It makes sense and now it's now clear how Dagger performs the optimization of parallel programs.
