### ISSUE TITLE
@par not defined

### ISSUE THREAD

**Issue by prosoitos** [JuliaParallel/Dagger.jl#207]
When trying to use `@par`, I am getting:

> ERROR: LoadError: UndefVarError: @par not defined
in expression starting at REPL[3]:1

`@par` is mentioned in the Dagger doc, but I don't know which module or package it comes from.

**Comment by jpsamaroo** [comment]
Yeah, you need to qualify it with the module since `@par` is not exported (for now). This should work: `Dagger.@par ...`

**Comment by prosoitos** [comment]
Oh, ok. Sorry: I didn't realize that it came with Dagger 🙄 Sorry for a bit of a silly question: this should have been the very first thing to try...

Thank you.

**Comment by jpsamaroo** [comment]
No problem at all!

**Comment by trickster** [comment]
@jpsamaroo 

I have the same issue. Why not export the macro from the module?

```
❯ julia -q
julia> using Distributed; addprocs()
12-element Vector{Int64}:
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13

julia> using Dagger

julia> add1(value) = value + 1
add1 (generic function with 1 method)

julia> add2(value) = value + 2
add2 (generic function with 1 method)

julia> combine(a...) = sum(a)
combine (generic function with 1 method)

julia> s = Dagger.@par begin
           p = add1(4)
           q = add2(p)
           r = add1(3)
           combine(p, q, r)
       end
ERROR: LoadError: UndefVarError: @par not defined
in expression starting at REPL[7]:1

julia> import Dagger: @par
WARNING: could not import Dagger.@par into Main
```

**Comment by jpsamaroo** [comment]
What version of Dagger are you using? `Dagger.@par` should work fine.

And it's not exported since it's the sort of macro name that I'd expect other packages to also use for their own purposes, so I didn't want name clashes. You can always do `import Dagger: @par`.

**Comment by trickster** [comment]
I tried the example I shared on Windows, didn't work for some reason. Tried the same on my mac, it worked.

**Comment by jpsamaroo** [comment]
You're almost definitely using an old version of Dagger on Windows.

**Comment by trickster** [comment]
I think so, I created new Windows VM and checked it again, it worked. My original Dagger version is off.
