### ISSUE TITLE
Revitalize file I/O, aka swap-to-disk

### ISSUE THREAD

**Issue by jpsamaroo** [JuliaParallel/Dagger.jl#214]
It's not actively tested or maintained, so we have to decide if we want to remove it, or if we want to modernize it and start testing that it works for out-of-core.

**Comment by shashi** [comment]
We should remove it and use FileTrees.jl

**Comment by jpsamaroo** [comment]
Could FileTrees gain some logic to allow saving/loading a filetree from/to a DArray? That would mimic some of the code we're removing.

**Comment by shashi** [comment]
Ehh maybe that's one level too extra of an abstraction.

You can couple of functions behind `@requires FileTrees` here which just load and save arrays by turning them into FileTrees.

**Comment by shashi** [comment]
Ideally this would move to DaggerArrays and then you wouldn't need the `@requires`

**Comment by jpsamaroo** [comment]
Alternatively, I think everyone could benefit from the scheduler having a basic understanding of memory pressure and have the option for data to be moved to disk when we're nearing an OOM situation (whether by mmap or Ser/Des). This could tie in nicely with the checkpointing API: even if checkpointing isn't enabled by the user, the scheduler could still decide to checkpoint (and simultaneously evict data from memory) if the data is bulky and it's expected that it won't be accessed in the short term.

**Comment by jpsamaroo** [comment]
Here's my plans for a "storage subsystem" that I'm working on:
- `Storage` abstract type, currently a subtype of `Processor` to let it fit the `move()` dispatch
- Memory/disk capacity awareness (per `Storage` object), communicated to (and estimated by) the Sch scheduler
- Memory usage tracking per-signature during execution via `Base.gc_num` (although this is inaccurate, being for all threads)
- "Storage scheduler" local to each worker which keeps all storage objects within capacity limits
- Some sort of redirection for a `Chunk` whose data is potentially no longer stored directly in memory, but is stored somewhere else. This lets us not have to update `Chunk` arguments for thunks we haven't yet seen in the Sch/storage scheduler.
- Move `CHUNK_CACHE` logic into storage scheduler, and let it track all local versions of a `Chunk`'s data
- Storage scheduler can evict data from any storage location and store it somewhere else, and even evict it entirely if it's not owned by the local worker
- The owner of a `Chunk` always keeps at least a single copy of the data around locally
- Some way to represent storage objects with overlapping backing devices (like when we have two storage objects saving things in different directories but on the same filesystem)
- Method to determine whether two workers have shared storage objects (network drives, or workers on the same host)

**Comment by jpsamaroo** [comment]
95% of this is implemented in MemPool now, so closing this.
