### ISSUE TITLE
Dagger doesn't detect threads as Processors after v0.11.3

### ISSUE THREAD

**Issue by krynju** [JuliaParallel/Dagger.jl#235]
Somewhere after v0.11.3 the threads that julia is spawned with are not detected and not utilized.
I checked on v0.11.3 and it works well - both detection and utilization

```julia
julia> Context().procs
1-element Vector{Dagger.Processor}:
 OSProc(1, Dict{Symbol, Any}(), Dagger.Processor[Dagger.ThreadProc(1, 1), Dagger.ThreadProc(1, 2),Dagger.ThreadProc(1, 3), Dagger.ThreadProc(1,4)], Dagger.Processor[])

julia> Threads.nthreads()
4
```

On master/v0.11.4 it's broken (no detection and utilization)
```julia
julia> Threads.nthreads()
4

julia> Context().procs
1-element Vector{Dagger.Processor}:
 OSProc(1)
```

Note: processes are detected properly on master and utilized as well

**Comment by krynju** [comment]
Ok, managed to get thread utilization on master, so seems like they're detected and utilized.
Just not visible under Context()

**Comment by jpsamaroo** [comment]
> Just not visible under Context() anymore after v0.11.3

What do you mean by this? All that changed is that the children processors are no longer stored in `OSProc` so that it can be more efficiently serialized, so now it won't show the processors in `Base.show(io, ::OSProc)`. However, you can see them in `Dagger.OSPROC_CACHE`.

**Comment by krynju** [comment]
On v0.11.3 you have the child processors there and that was to me a good indicator that they were in fact visible to Dagger.

In the docs there was that example with `addprocs!` called on a `Context` to create a custom execution setup that would, for example, not utilize all the available processes (https://juliaparallel.github.io/Dagger.jl/dev/processors/#Dynamic-worker-pools).

So going by the docs you would probably look for the execution setup in the `Context` object. If that's not there now then realistically there's no public function to see the thread setup right after launch (the cache populates on the first use of the scheduler I suppose)

```julia
julia> Threads.nthreads()
8

julia> using Dagger

julia> Dagger.OSPROC_CACHE
Dict{Int64, Vector{Dagger.Processor}}()

julia> Dagger.@spawn 10+10
EagerThunk (running)

julia> Dagger.OSPROC_CACHE
Dict{Int64, Vector{Dagger.Processor}} with 1 entry:
  1 => [ThreadProc(1, 1), ThreadProc(1, 2), ThreadProc(1, 3), ThreadProc(1, 4), ThreadProc(1, 5), ThreadProc(1, 6), Thr…
```

**Comment by jpsamaroo** [comment]
> that was to me a good indicator that they were in fact visible to Dagger.

I agree that this is a regression in visibility into available processors. We could implement a better `Base.show` for `OSProc` and for `Context`; this would be a pretty easy PR, if you're interested.

> If that's not there now then realistically there's no public function to see the thread setup right after launch (the cache populates on the first use of the scheduler I suppose)

Yeah, that is rather annoying. Thankfully, constructing an `OSProc` with a new PID causes the `OSPROC_CACHE` to be populated for that worker, so just showing an `OSProc` or a `Context` should be sufficient even before any computations have been run.
