### ISSUE TITLE
Eager API example from Readme.md won't work

### ISSUE THREAD

**Issue by krynju** [JuliaParallel/Dagger.jl#241]
I caught a glimpse of the new readme and noticed that the code example will not execute due to this small inconvenience

```julia
julia> c = Dagger.@spawn sum(b)+a
ERROR: MethodError: no method matching iterate(::Dagger.EagerThunk)
```

I noticed a lot of these when prototyping on DTables, so I usually work around them by wrapping the code in a function and using the macro on it with thunk arguments like this:

```julia
julia> c = Dagger.@spawn ((a,b)->sum(b)+a)(a,b)
EagerThunk (running)

julia> fetch(c)
13.881714780482696
```

I didn't really dig much into this, but I noticed this issue that might be related https://github.com/JuliaParallel/Dagger.jl/issues/216

**Comment by jpsamaroo** [comment]
Thanks for the catch! Fixed in https://github.com/JuliaParallel/Dagger.jl/commit/247f0ba576150fae348e394a41f322e9d0fbabaf.
