### ISSUE TITLE
make unit test results visible to all

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaParallel/Dagger.jl#257]
Perhaps I'm missing something, but I don't seem to be able to see the results of any of the unit tests in PR's.  This worries me as users should be able to see test results to give them the confidence they need to use the package.  I wonder what is the reason for using buildkite?  I would be glad to help switching to github workflow if you're interested.

**Comment by vchuravy** [comment]
I am not sure what you mean:

I can visit as an example
https://buildkite.com/julialang/dagger-dot-jl/builds/231#457e6907-8b0f-466e-bc62-b59d500949b1

in an anonymous browser, as well as seeing the status on the PR

**Comment by ExpandingMan** [comment]
That is so weird... as of this moment when I look in the run lists for the currently active PR I can seethe buildkite links... maybe I'm losing my mind but I *could have sworn* I was not seeing them before...

Ok, feeling very confused, but I will close this issue unless I encounter the problem again...
