### ISSUE TITLE
AppVeyor for 1.3 target: scopes testing fails due to -t usage

### ISSUE THREAD

**Issue by krynju** [JuliaParallel/Dagger.jl#266]
https://github.com/JuliaParallel/Dagger.jl/blob/0b72b7762a061dd57beb6abe12fbbce1ebdbfed8/test/scopes.jl#L2

Here's there's a -t2 and it was only introduced in 1.5. 
export JULIA_NUM_THREADS=2 is required pre-1.5, but env kwarg was also added only at 1.6

can't remember how to do that without just having it in the .bashrc on the machine pre1.5

**Comment by jpsamaroo** [comment]
No longer necessary as of https://github.com/JuliaParallel/Dagger.jl/pull/278/commits/7b4c1dbf287b9a75f9311306e334680067e6be8a
