### ISSUE TITLE
`EagerThunk`s and logging

### ISSUE THREAD

**Issue by nucklass** [JuliaParallel/Dagger.jl#268]
Hi! Just caught the JuliaCon vod and am really excited for the new DTable api. I've been working with the new Eager api for the past few days and have been attempting to log the toy examples for the `@spawn` macro  to mixed success. After reading through the source code, I figured this would work: 
```
using Distributed
addprocs()

using Dagger
Dagger.Sch.init_eager()
log = Dagger.LocalEventLog()
Dagger.Sch.EAGER_CONTEXT[].log_sink = log

x =  Dagger.@spawn rand(400,400)
y =  Dagger.@spawn rand(400,400)
zt = Dagger.@spawn (x * y)
z = fetch(zt)

logs = Dagger.get_logs!(log)
str = Dagger.show_plan(logs)
```
I've  run this a few times in the REPL and noticed I'll sometimes get a proper log and digraph, but more often I'll just get an empty Timespan and digraph. I haven't been able to pin down the seemingly inconsistent results. Is the above the proper way to log the background scheduler? If so, am I missing something about how the logger works? 

Thanks!
EDIT: Looks like I'm mainly getting logs when something errors, usually a `concurrency_violation`.

**Comment by jpsamaroo** [comment]
This looks about right to me! I suspect this is happening because the scheduler sometimes only launches work on worker 1, and https://github.com/JuliaParallel/Dagger.jl/blob/0b72b7762a061dd57beb6abe12fbbce1ebdbfed8/src/lib/logging.jl#L247 doesn't capture worker 1 (since `workers()` only returns the other workers when there is more than 1).

I'll be posting a PR soon that greatly overhauls the logging code and implements a new, fancy web dashboard for displaying everything, so I'll make sure to fix this in that PR as well. In the meantime, feel free to change `workers()` in that line to `vcat(1, workers())`.

Also, can you post the concurrency violation errors you get with a full stacktrace?

**Comment by nucklass** [comment]
Thanks! I figured that line was the issue after forking the repo last night and doing a few `spawn` calls with `single` set. I can post the stack trace once I get back to my laptop. Am I all set to make a PR to change that line in logging.jl or do you just recommend doing it locally for now? 
Also, feel free to contact me if you need an extra set of hands on the web dashboard or anything else; I’ve been doing work with PySpark lately and it would be great to have a more fleshed out, pure-Julia alternative  so I don’t have to debug JVM stuff so often.

**Comment by jpsamaroo** [comment]
> Am I all set to make a PR to change that line in logging.jl or do you just recommend doing it locally for now?

Yes please! My logging PR might take some time, and we'd fix it the same way anyway.

> Also, feel free to contact me if you need an extra set of hands on the web dashboard or anything else; I’ve been doing work with PySpark lately and it would be great to have a more fleshed out, pure-Julia alternative so I don’t have to debug JVM stuff so often.

Thanks for the offer! Do you have any D3.js experience? I'm building it out with D3 client-side rendering, which has been far easier than the previous approach of server-side rendering with Luxor.jl (using Cairo). But my D3 knowledge is a little rusty, being a few years old, so it's taking me a while to get things working the way I want.

**Comment by krynju** [comment]
I have this piece of code for that use case and never really had any issues with it, so you can try it
Just note that it clears the log every time you run that write to the file.
Also have a version with `clipboard()` somewhere quickly paste it to an online graphviz viewer.

```julia
Dagger.@spawn 10 + 10 # to init scheduler
log = Dagger.LocalEventLog()
Dagger.Sch.EAGER_CONTEXT.x.log_sink = log
open("log.txt", "w") do io # run this every time you want to collect a log
    logs = Dagger.get_logs!(log)
    write(io, Dagger.show_plan(logs))
end;
```

**Comment by nucklass** [comment]
> Thanks for the offer! Do you have any D3.js experience? I'm building it out with D3 client-side rendering, which has been far easier than the previous approach of server-side rendering with Luxor.jl (using Cairo). But my D3 knowledge is a little rusty, being a few years old, so it's taking me a while to get things working the way I want.

I'm a bit rusty myself, but certainly wouldn't mind throwing myself at observablehq and the docs  to try and figure things out if you're open to it and have other things on your plate. Is there a branch open with a prototype in place? 

>I have this piece of code for that use case and never really had any issues with it, so you can try it
Also have a version with clipboard() somewhere quickly paste it to an online graphviz viewer.

Thank you! I'll give this a shot as well having the log in an external file sounds very useful.
