### ISSUE TITLE
rename gather to collect 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/Dagger.jl#27]
@shashi @MikeInnes I have been thinking about the suggestion of `collect` instead of `gather` and quite like it.

**Comment by shashi** [comment]
the semantics of `collect` is to always return a vector. This should probably be `convert(Array, x)`.

**Comment by shashi** [comment]
As an alias to gather.

**Comment by richardreeve** [comment]
That is no longer true of `collect` in v0.5:
```{julia}
julia> collect(1.0)
0-dimensional Array{Float64,0}:
1.0

julia> collect([1.0])
1-element Array{Float64,1}:
 1.0

julia> collect([1.0 1.0; 1.0 1.0])
2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0
```

`vec` now always returns a vector. This broke my package a few weeks ago. I think in that context `collect` would be a good name for it rather than `gather`.

**Comment by shashi** [comment]
@richardreeve thanks for pointing that out!

It seems that `collect` also creates a copy of the input array. but `convert(Array, x)` doesn't. So it's better to use convert for generic code that you want to work on both Julia arrays and LazyArrays. I think the right thing to do here would be make `convert(Array, x)` and `collect` do the same thing, and deprecate `gather`.

**Comment by richardreeve** [comment]
@shashi that makes sense to me, to avoid creating new terms where existing ones have the same meaning (or at least it does now I've [been forced to!] accept that `collect` has changed its meaning).

**Comment by shashi** [comment]
Done!
