### ISSUE TITLE
Faster filtering in Dagger

### ISSUE THREAD

**Issue by PingoLee** [JuliaParallel/Dagger.jl#272]
I need to perform multiple filtering steps (thousands) and Dagger was too slow. How can I perform faster filtering in Dagger?

```
julia> df = DataFrame(A = rand(1:10, N), B = rand(1:100, N))
10000×2 DataFrame
   Row │ A      B     
       │ Int64  Int64 
───────┼──────────────
     1 │     6     91
     2 │     8     39
     3 │     3     88
   ⋮   │   ⋮      ⋮
  9998 │     3     32
  9999 │     2     94
 10000 │     3     46
     9994 rows omitted

julia> @time d = DTable(df, 2; tabletype=DataFrame)
  0.049015 seconds (582.98 k allocations: 28.276 MiB)
DTable with 5000 partitions
Tabletype: DataFrame

julia> @time f = filter(x -> x.A == 1, d)
  2.679566 seconds (10.54 M allocations: 691.816 MiB, 15.09% gc time, 23.86% compilation time)
DTable with 5000 partitions
Tabletype: DataFrame

julia> @time fetch(f)
  1.560662 seconds (6.70 M allocations: 468.358 MiB, 15.03% gc time)
973×2 DataFrame
 Row │ A      B     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     16
   2 │     1     41
   3 │     1     67
  ⋮  │   ⋮      ⋮
 971 │     1     22
 972 │     1     17
 973 │     1     26
    967 rows omitted

julia> @time df2 = filter([:A] => (x) -> x ==  1  , df)
  0.100892 seconds (426.64 k allocations: 24.575 MiB, 99.59% compilation time)
973×2 DataFrame
 Row │ A      B     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     16
   2 │     1     41
   3 │     1     67
  ⋮  │   ⋮      ⋮
 971 │     1     22
 972 │     1     17
 973 │     1     26
    967 rows omitted

julia> @time q1 = @from j in df begin
           @where j.A ==  1
           @select j
           @collect DataFrame
       end
  0.039823 seconds (209.21 k allocations: 12.133 MiB, 99.62% compilation time)
973×2 DataFrame
 Row │ A      B     
     │ Int64  Int64 
─────┼──────────────
   1 │     1     16
   2 │     1     41
   3 │     1     67
  ⋮  │   ⋮      ⋮
 971 │     1     22
 972 │     1     17
 973 │     1     26
    967 rows `omitted`
```

**Comment by PingoLee** [comment]
Something very strange happened, I couldn't run all the tests, it took too long.

```
julia> N =10_000
10000

julia> df = DataFrame(A = rand(1:10, N), B = rand(1:100, N))
10000×2 DataFrame
   Row │ A      B     
       │ Int64  Int64 
───────┼──────────────
     1 │     8     52
     2 │     5     44
     3 │     4     86
   ⋮   │   ⋮      ⋮
  9998 │    10     66
  9999 │     6     19
 10000 │     7      7
     9994 rows omitted

julia> @btime d = DTable(df, 2; tabletype=DataFrame)
  50.054 ms (602984 allocations: 28.89 MiB)
DTable with 5000 partitions
Tabletype: DataFrame

julia> @btime f = filter(x -> x.A == 1, d)
  5810.295 s (12947899573 allocations: 729.75 GiB)
DTable with 50000 partitions
Tabletype: DataFrame

julia> @btime fetch(f)
```

**Comment by jpsamaroo** [comment]
@krynju 

Those times for construction and especially filtering are very concerning. What's also weird is the "50000 partitions" being printed as the result of the filter operation.

**Comment by krynju** [comment]
@PingoLee Overall the best practice is to have fewer partitions. For example each one being ~50MB approximately.
That will reduce the construction time and filter time. 
Also make sure you have launched julia with some threads or processes, so that dagger can use the additional workers.

Here by changing the partitionsize to 1_000 the speed gain is significant compared to size 2.
Now on small examples DataFrames will always be faster, but I included an example where the multithreading from Dagger allowed the DTable filter to be faster than DataFrames

```julia
julia> using Dagger, DataFrames, BenchmarkTools

julia> versioninfo()
Julia Version 1.8.0-DEV.359
Commit e8faf9d17b (2021-08-17 08:43 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 5800X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver3)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 16

julia> N = 10_000;

julia> df = DataFrame(A = rand(1:10, N), B = rand(1:100, N));

julia> d2 = DTable(df, 2; tabletype=DataFrame)
DTable with 5000 partitions
Tabletype: DataFrame

julia> d1000 = DTable(df, 1000; tabletype=DataFrame)
DTable with 10 partitions
Tabletype: DataFrame

julia> @btime fetch(filter(x -> x.A == 1, d2));
  4.392 s (16081160 allocations: 1.02 GiB)

julia> @btime fetch(filter(x -> x.A == 1, d1000));
  4.568 ms (73454 allocations: 2.58 MiB)

julia> @btime filter(x-> x.A == 1, df);
  752.700 μs (39511 allocations: 803.30 KiB)


julia> N = 100_000_000
100000000

julia> df = DataFrame(A = rand(1:10, N), B = rand(1:100, N));

julia> d = DTable(df, 1_000_000; tabletype=DataFrame)
DTable with 100 partitions
Tabletype: DataFrame

julia> @btime fetch(filter(x -> x.A == 1, d));
  6.560 s (780699571 allocations: 15.29 GiB)

julia> @btime filter(x-> x.A == 1, df);
  8.232 s (400013960 allocations: 7.69 GiB)
```

**Comment by krynju** [comment]
@PingoLee 
I can't replicate your recent comment https://github.com/JuliaParallel/Dagger.jl/issues/272#issuecomment-907549872
Can you please share more details on julia and dagger version?

**Comment by PingoLee** [comment]
Hi,  @krynju 
I would like to replace PowerBI, and for that I need to do multiple filtering operations. For example, the smallest dataset (13,000 x 22,000) takes 1 minute to process (filter df1 information in df2), but I have much larger datasets (500,000 x 2,000,000). Any ideas of options I would have?

```
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 5600X 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, generic)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

(ESUS_SQL_WEB_jl) pkg> status Dagger
      Status `C:\Users\rafa\Desktop\Sites\Genie\ESUS_SQL_WEB_jl\Project.toml`
  [d58978e5] Dagger v0.13.1
```

**Comment by krynju** [comment]
Sounds like a production use case. I would recommend DataFrames as that is probably the most mature table package around.
But most likely it won't be the only required package to cover your need end to end, so you'll need to look at other packages as well to figure out what works best for you

If you need help in designing your solution I think the best place to ask would be julia's discourse or slack

**Comment by PingoLee** [comment]
Thank you @krynju. I work with public health data, so the amount of information is huge. Thanks for the collaboration, I will keep looking.

**Comment by jpsamaroo** [comment]
@PingoLee note that @krynju isn't saying that Dagger isn't suitable for your task and won't ever be, but instead that it's not necessarily ready *right now* for production use cases. If you're doing this processing "offline" (not as part of an EHR database system, for example), then I think the `Dagger.DTable` is worth trying out to net yourself some performance gains over a simple `DataFrame`. I'd only be concerned if you were using the `DTable` for some real-time, business-critical system. Dagger as a whole is not yet ready for such use cases (but will be as time goes on).
