### ISSUE TITLE
DTable missing in Documentation API list

### ISSUE THREAD

**Issue by felixcremer** [JuliaParallel/Dagger.jl#302]
The DTable type is missing in the API type list of the documentation https://juliaparallel.github.io/Dagger.jl/stable/api/types/

Should this list be automatically generated, so that it will update with the code?

**Comment by jpsamaroo** [comment]
Good catch! Fixed in #303 

> Should this list be automatically generated, so that it will update with the code?

That would be great! We should probably generate docs for any exported function.
