### ISSUE TITLE
DaggerWebDash not starting

### ISSUE THREAD

**Issue by deyandyankov** [JuliaParallel/Dagger.jl#319]
I have a clean Julia 1.7 install with just Dagger and DaggerWebDash running on ubuntu. I'm unable to start the dagger dashboard as per the below mwe:

``` julia
stester@euler:~$ BENCHMARK_RENDER=webdash julia -t 4
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [d58978e5] Dagger v0.14.1
  [cfc5aa84] DaggerWebDash v0.1.1

julia> ENV["BENCHMARK_RENDER"]
"webdash"

julia> using Dagger

julia> using DaggerWebDash

julia> for i in 1:100
                  r = fetch(Dagger.@spawn rand(100_000))
                  @info "Fetched $(length(r)) random values. Sleeping for a second."
                  sleep(1)
              end

[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[ Info: Fetched 100000 random values. Sleeping for a second.
[...]
```

I was expecting DaggerWebDash to bind on :8000 but this is not the case - have confirmed using `netstat`.
I'm following the [development documentation](https://juliaparallel.github.io/Dagger.jl/dev/scheduler-visualization/).

Thank you for looking into this.

**Comment by deyandyankov** [comment]
I also tried the following instead:
```
using Distributed
using Dagger
@everywhere using DaggerWebDash
```
after watching [this video](https://www.youtube.com/watch?v=capjmjVHfMU) -- but dashboard still doesn't start

**Comment by jpsamaroo** [comment]
From the docs:

> Using the dashboard is relatively simple and straightforward; if you run Dagger's benchmarking script, it's enabled for you automatically if the BENCHMARK_RENDER environment variable is set to webdash. This is the easiest way to get started with the web dashboard for new users.

> For manual usage, the following snippet of code will suffice:

And then a large snippet of code is provided, which you need to execute if you are just running Dagger manually (i.e. not via the `benchmark.jl` script). Loading DaggerWebDash doesn't start the dashboard; you need to configure the logging in Dagger, using pieces from DaggerWebDash, to get it started. Dagger's new logging and visualization facilities are intentionally designed this way to be extremely flexible and extensible beyond just the built-in dashboard.

**Comment by deyandyankov** [comment]
Thanks a lot for the explanation. I'll tinker a bit more with what's provided in the docs. Closing the issue for now.
