### ISSUE TITLE
DaggerWebDash using old libs

### ISSUE THREAD

**Issue by Roh-codeur** [JuliaParallel/Dagger.jl#365]
Hi 

DaggerWebDash is an amazing package. however, It appears DaggerWebDash is using a few old libs which prevent me from updating other libs. Do you think we can look at upgrading some of the older libs please?

ta!

**Comment by krynju** [comment]
I suppose the Mux compat on HTTP is holding you back - I don't think it will be difficult to move to Mux 1.0 
@jpsamaroo

**Comment by Roh-codeur** [comment]
yes please, thanks

**Comment by Roh-codeur** [comment]
thanks @jpsamaroo and @krynju
