### ISSUE TITLE
Block distribution incompatibility in matmul should fail better

### ISSUE THREAD

**Issue by shashi** [JuliaParallel/Dagger.jl#47]
```julia
X1 = Distribute(BlockPartition(10, 20), X)
@test_throws DimensionMismatch compute(X1*X1)
```
But throws an alarming BoundsError

**Comment by jpsamaroo** [comment]
This throws `DimensionMismatch` on master as desired, so I'm going to close this issue. Do please re-open if you have another example with fails with an inappropriate error.
