### ISSUE TITLE
Updating to Documenter.jl v1

### ISSUE THREAD

**Issue by JamesWrigley** [JuliaParallel/Dagger.jl#482]
I attempted to update the docs to build with Documenter.jl v1, but it seems that there are dependency conflicts. I narrowed it down to:
- The docs project depending on `DaggerWebDash`
  - Which depends on [ProfileSVG.jl](https://github.com/kimikage/ProfileSVG.jl)
    - Which has a [compat bound](https://github.com/kimikage/ProfileSVG.jl/blob/master/Project.toml#L13) to [FlameGraphs.jl](https://github.com/timholy/FlameGraphs.jl) v0.2 (an old version)
      - Which has a [compat bound](https://github.com/timholy/FlameGraphs.jl/blob/v0.2.10/Project.toml#L16) to an old version of AbstractTrees.jl
        - Which is incompatible with Documenter.jl v1: https://github.com/JuliaDocs/Documenter.jl/blob/master/Project.toml#L32
        
This PR would fix it: https://github.com/kimikage/ProfileSVG.jl/pull/70
But I'm not sure if that'll get merged anytime soon. Anyway it's not urgent, I just wanted to document the chain of pain :grin:

**Comment by jpsamaroo** [comment]
Thanks for looking into this! I'd be ok with removing ProfileSVG support from DaggerWebDash for now - it's not really used, since profiling support in Dagger isn't great, because Profile doesn't support continuous profiling (yet another chain of pain :laughing: ).

**Comment by asinghvi17** [comment]
If it's a web viewer, you could try switching to ProfileCanvas.jl instead?  Not sure if it needs a live server, though.

Alternatively, you can always just add that branch in CI explicitly!

**Comment by jpsamaroo** [comment]
The live rendering support is enabled by running ProfileSVG multiple times, so ProfileCanvas.jl could work! Thanks for letting me know about it :smile:

**Comment by JamesWrigley** [comment]
Fixed in #487.
