### ISSUE TITLE
Dagger documentation does not build locally

### ISSUE THREAD

**Issue by wolthom** [JuliaParallel/Dagger.jl#552]
While working on a PR to the documentation, I have encountered the issue that the documentation does not build without local changes.

Specifically, I get the following error:
![image](https://github.com/user-attachments/assets/7b5041b7-5038-4a24-b2a3-2b46d4500281)

This can be worked around by removing the `@docs` marker in the corresponding code snippet in `src/api-timespanlogging/functions.md` (without committing this change, of course).
In CI this does appear to build successfully due to locally dev'ed packages(?).

Is there a good way to fix this?

**Comment by JamesWrigley** [comment]
No I don't think so, until we can specify the subpackges in `[sources]`: https://github.com/JuliaLang/Pkg.jl/pull/3783

For now you'll need to `] dev lib/TimespanLogging` etc.
