### ISSUE TITLE
MethodError with save function while trying out the example code

### ISSUE THREAD

**Issue by ghost** [JuliaParallel/Dagger.jl#65]
I am using the dagger version 0.2.1 and julia version 0.6.0.  I was trying to do the example code from the README.md file:

`addprocs()`
`using Dagger`
`A = rand(Blocks(4000, 4000), 30000, 30000) # 7.2GB of data`
`saved_A = compute(save(A, "A"))`

`result = compute(save(saved_A+saved_A', "ApAt"))`

which is under the section "A note on keeping memory use in check".  In particular,  i received  the following error:

ERROR: MethodError: no method matching save(::String, ::Dagger.AllocateArray{Float64,2})
Closest candidates are:
  save(::Any, ::IO, ::Dagger.Chunk, ::Any) at /home/jrb/.julia/v0.6/Dagger/src/file-io.jl:55
  save(::Any, ::IO, ::Dagger.DArray, ::AbstractString, ::AbstractArray) at /home/jrb/.julia/v0.6/Dagger/src/file-io.jl:72
  save(::Any, ::IO, ::Dagger.DArray, ::Any) at /home/jrb/.julia/v0.6/Dagger/src/file-io.jl:84

when trying to execute the line

`saved_A = compute(save(A, "A"))`

Please let me know if I could provide you with any other details or if I just made a silly error.

**Comment by pelagisk** [comment]
I had the same problem! On a 2016 MacBook Air with Julia 0.6.1 and Dagger version 0.5.0.

Any news on this? I tried also `compute(save(A..., "A"))` but then the REPL froze while using 25% of the processor and about 2.5 GB of RAM.

**Comment by jpsamaroo** [comment]
After speaking with @shashi, I don't believe we intend for Dagger to support this functionality any longer. An alternative is available in [FileTrees](https://github.com/shashi/FileTrees.jl), although saving and loading is left up to the user (as it should be). We'll be extracting the array interface from Dagger in the next few months, so I'm closing this issue.
